import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class MoviesService {


  movies: {}[] = [
    {
      title: 'Unhinged',
      slug: 'unhinged',
      // tslint:disable-next-line: max-line-length
      cover: 'https://m.media-amazon.com/images/M/MV5BZTI0ZGIxZTEtMWQxMi00MDVhLWFmNWQtNmU5ZWNhYjJmYjJkXkEyXkFqcGdeQXVyMDA4NzMyOA@@._V1_SY1000_CR0,0,666,1000_AL_.jpg',
      trailer: 'https://www.youtube.com/watch?v=1EtytOgGj5o',
      releaseDate: '10 July 2020',
      duration: '90 minutes',
      // tslint:disable-next-line: max-line-length
      synopsis: `Unhinged - Starring Russell Crowe, a psychological thriller that takes something we've all experienced- road rage - to an unpredictable and terrifying conclusion. Rachel (Caren Pistorius) is running late getting to work when she crosses paths with a stranger (Crowe) at a traffic light. Soon, Rachel finds herself and everyone she loves the target of a man who feels invisible and is looking to make one last mark upon the world by teaching her a series of deadly lessons. What follows is a dangerous game of cat and mouse that proves you never know who you're driving next to. Buy Unhinged movie tickets and get showtimes at Regal theatres, on the Regal mobile app or online. Discover movie trailers and view upcoming movies at www.regmovies.com. Stop by a Moviak theater near you today.`,
      genre: '',
      cast: `Russell Crowe, Gabriel Bateman, Caren Pistorius, Anne Leighton, Jimmi Simpson`,
      Director: 'Derrick Borte',
      production: '2020',
      restrictions: 'NR',
      seats: [
        'available',
        'available',
        'reserved',
        'available',
        'available',
        'reserved',
        'available',
        'available',
        'available',
        'available',
        'reserved',
        'available',
        'available',
        'available',
        'available',
        'reserved',
        'available',
        'available',
        'available',
        'reserved',
        'available',
        'available',
        'available',
        'available',
        'reserved',
        'available',
        'available',
        'available',
        'available',
        'available',
        'available',
        'available',
        'reserved',
        'available',
        'available',
        'available',
        'reserved',
        'available',
        'reserved',
        'available',
        'available',
        'reserved',
        'available',
        'available',
        'reserved',
      ]
    },
    {
      title: 'Tenet',
      slug: 'tenet',
      // tslint:disable-next-line: max-line-length
      cover: 'https://m.media-amazon.com/images/M/MV5BNmMwYzFlNTEtYTc0NC00NGY4LTgzNzItZGFiYTViY2QzNzU1XkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_SY1000_CR0,0,674,1000_AL_.jpg',
      trailer: 'https://www.youtube.com/watch?v=L3pk_TBkihU',
      releaseDate: '31 July 2020',
      duration: '120 minutes',
      // tslint:disable-next-line: max-line-length
      synopsis: `Tenet - An action epic revolving around international espionage, time travel, and evolution. Possibly about a man trying to prevent World War 3 through time travel and rebirth. Buy Tenet movie tickets and get showtimes at Regal theatres, on the Regal mobile app or online. Discover movie trailers and view upcoming movies at www.regmovies.com. Stop by a Moviak theater near you today.`,
      genre: 'Action, Drama',
      // tslint:disable-next-line: max-line-length
      cast: `Kenneth Branagh, Michael Caine, Robert Pattinson, Elizabeth Debicki, John David Washington, Aaron Taylor-Johnson, Clémence Poésy, Dimple Kapadia`,
      Director: 'Christopher Nolan',
      production: '2020',
      restrictions: 'NR',
      seats: [
        'available',
        'available',
        'reserved',
        'available',
        'available',
        'reserved',
        'available',
        'available',
        'available',
        'available',
        'reserved',
        'reserved',
        'available',
        'reserved',
        'available',
        'reserved',
        'available',
        'available',
        'available',
        'reserved',
        'available',
        'available',
        'available',
        'available',
        'reserved',
        'available',
        'available',
        'available',
        'reserved',
        'available',
        'available',
        'available',
        'reserved',
        'available',
        'available',
        'available',
        'reserved',
        'available',
        'reserved',
        'available',
        'available',
        'reserved',
        'available',
        'available',
        'reserved',
      ]
    },
    {
      title: 'Mulan (2020)',
      slug: 'mulan-2020',
      // tslint:disable-next-line: max-line-length
      cover: 'https://m.media-amazon.com/images/M/MV5BMjFlZjZkMTYtODM2Zi00OTM4LWIwYTktOTFjMmQzZDEzZDc4XkEyXkFqcGdeQXVyNDg4NjY5OTQ@._V1_SY1000_CR0,0,675,1000_AL_.jpg',
      trailer: 'https://www.youtube.com/watch?v=KK8FHdFluOQ',
      releaseDate: '24 July 2020',
      duration: '115 minutes',
      // tslint:disable-next-line: max-line-length
      synopsis: `Disney's Mulan. Acclaimed filmmaker Niki Caro brings the epic tale of China's legendary warrior to life, in which a fearless young woman risks everything out of love for her family and her country to become one of the greatest warriors China has ever known. When the Emperor of China issues a decree that one man per family must serve in the Imperial Army to defend the country from Northern invaders, Hua Mulan, the eldest daughter of an honored warrior, steps in to take the place of her ailing father. Masquerading as a man, Hua Jun, she is tested every step of the way and must harness her inner-strength and embrace her true potential. It is an epic journey that will transform her into an honored warrior and earn her the respect of a grateful nation.and a proud father. "Mulan" features a celebrated international cast that includes: Yifei Liu as Mulan; Donnie Yen as Commander Tung; Jason Scott Lee as Böri Khan; Yoson An as Cheng Honghui; with Gong Li as Xianniang and Jet Li as the Emperor. The film is directed by Niki Caro from a screenplay by Rick Jaffa & Amanda Silver and Elizabeth Martin & Lauren Hynek based on the narrative poem "The Ballad of Mulan." Buy Mulan movie tickets and get showtimes at Regal theatres, on the Regal mobile app or online. Discover movie trailers and view upcoming movies at www.regmovies.com. Stop by a Moviak theater near you today.`,
      genre: 'Action',
      // tslint:disable-next-line: max-line-length
      cast: `Jet Li, Yifei Liu, Donnie Yen, Jason Scott Lee, Yoson An, Gong Li`,
      Director: 'Niki Caro',
      production: '2020',
      restrictions: 'PG13',
      seats: [
        'available',
        'available',
        'reserved',
        'available',
        'available',
        'reserved',
        'available',
        'available',
        'available',
        'available',
        'reserved',
        'available',
        'available',
        'available',
        'available',
        'reserved',
        'reserved',
        'available',
        'available',
        'reserved',
        'available',
        'available',
        'available',
        'available',
        'reserved',
        'reserved',
        'available',
        'available',
        'available',
        'available',
        'available',
        'available',
        'reserved',
        'available',
        'available',
        'available',
        'reserved',
        'available',
        'reserved',
        'available',
        'available',
        'reserved',
        'available',
        'available',
        'reserved',
      ]
    },
    {
      title: 'Spongebob Movie: Sponge On The Run',
      slug: 'spongebob-movie-sponge-on-the-run',
      // tslint:disable-next-line: max-line-length
      cover: 'https://m.media-amazon.com/images/M/MV5BODIwMmQxNDktOWZjZC00NWI4LTg1NjktMGViOTE4ZTA4ZGY5XkEyXkFqcGdeQXVyNjg5MjU3NjE@._V1_SY1000_CR0,0,674,1000_AL_.jpg',
      trailer: 'https://www.youtube.com/watch?v=-XOuu1vd_fk',
      releaseDate: '07 August 2020',
      duration: '115 minutes',
      // tslint:disable-next-line: max-line-length
      synopsis: `After SpongeBob's beloved pet snail Gary is snail-napped, he and Patrick embark on an epic adventure to The Lost City of Atlantic City to bring Gary home. As they navigate the delights and dangers on this perilous and hilarious rescue mission, SpongeBob and his pals prove there's nothing stronger than the power of friendship. Buy The Spongebob Movie: Sponge On The Run movie tickets and get showtimes at Regal theatres, on the Regal mobile app or online. Discover movie trailers and view upcoming movies at www.regmovies.com. Stop by a Moviak theater near you today.`,
      genre: 'Comedy',
      // tslint:disable-next-line: max-line-length
      cast: `Tom Kenny, Clancy Brown, Rodger Bumpass, Bill Fagerbakke, Stephanie D'Abruzzo, Jill Talley`,
      Director: 'Tim Hill',
      production: '2020',
      restrictions: 'NR',
      seats: [
        'available',
        'available',
        'reserved',
        'available',
        'available',
        'reserved',
        'available',
        'available',
        'available',
        'available',
        'reserved',
        'available',
        'reserved',
        'available',
        'available',
        'reserved',
        'available',
        'available',
        'available',
        'reserved',
        'available',
        'available',
        'available',
        'available',
        'reserved',
        'available',
        'available',
        'reserved',
        'available',
        'available',
        'available',
        'available',
        'reserved',
        'available',
        'available',
        'available',
        'reserved',
        'available',
        'reserved',
        'available',
        'available',
        'reserved',
        'available',
        'available',
        'reserved',
      ]
    },
    {
      title: 'Black Widow',
      slug: 'black-widow',
      // tslint:disable-next-line: max-line-length
      cover: 'https://m.media-amazon.com/images/M/MV5BMzFiODE0ZDUtN2IxNC00OTI5LTg4OWItZTE2MjU4ZTk2NjM5XkEyXkFqcGdeQXVyNDYzODU1ODM@._V1_SY1000_CR0,0,674,1000_AL_.jpg',
      trailer: 'https://www.youtube.com/watch?v=ybji16u608U',
      releaseDate: '06 November 2020',
      duration: '115 minutes',
      // tslint:disable-next-line: max-line-length
      synopsis: `Marvel's Black Widow - Scarlett Johansson reprises her role as Natasha/Black Widow in Marvel Studios' action-packed spy thriller "Black Widow"-the first film in Phase Four of the Marvel Cinematic Universe. Florence Pugh stars as Yelena, David Harbour as Alexei aka The Red Guardian and Rachel Weisz as Melina. Directed by Cate Shortland and produced by Kevin Feige. Buy Black Widow movie tickets and get showtimes at Regal theatres, on the Regal mobile app or online. Discover movie trailers and view upcoming movies at www.regmovies.com. Stop by a Moviak theater near you today.`,
      genre: 'Action',
      // tslint:disable-next-line: max-line-length
      cast: `Rachel Weisz, Ray Winstone, Scarlett Johansson, Florence Pugh, David Harbour, O-T Fagbenle`,
      Director: 'Cate Shortland',
      production: '2020',
      restrictions: 'NR',
      seats: [
        'available',
        'available',
        'reserved',
        'available',
        'available',
        'reserved',
        'available',
        'available',
        'available',
        'available',
        'reserved',
        'available',
        'available',
        'available',
        'available',
        'reserved',
        'available',
        'available',
        'available',
        'reserved',
        'available',
        'available',
        'available',
        'available',
        'reserved',
        'available',
        'available',
        'available',
        'available',
        'available',
        'available',
        'available',
        'reserved',
        'available',
        'available',
        'available',
        'reserved',
        'available',
        'reserved',
        'available',
        'available',
        'reserved',
        'available',
        'available',
        'reserved',
      ]
    },
    {
      title: 'Free Guy',
      slug: 'free-guy',
      // tslint:disable-next-line: max-line-length
      cover: 'https://m.media-amazon.com/images/M/MV5BNzE5YzVjZmEtNGYwZi00YjljLWExMzYtZjlkYTk4NDc0MmI5XkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_SY1000_SX675_AL_.jpg',
      trailer: 'https://www.youtube.com/watch?v=X2m-08cOAbc',
      releaseDate: '11 December 2020',
      duration: '115 minutes',
      // tslint:disable-next-line: max-line-length
      synopsis: `Free Guy - A bank teller discovers he is a background character in an open world video game called Free City that will soon go offline. Buy Free Guy movie tickets and get showtimes at Regal theatres, on the Regal mobile app or online. Discover movie trailers and view upcoming movies at www.regmovies.com. Stop by a Moviak theater near you today.`,
      genre: 'Action',
      // tslint:disable-next-line: max-line-length
      cast: `Ryan Reynolds, Utkarsh Ambudkar, LilRel Howery, Taika Waititi, Joe Keery, Jodie Comer`,
      Director: 'Shawn Levy',
      production: '2020',
      restrictions: 'NR',
      seats: [
        'available',
        'available',
        'reserved',
        'available',
        'available',
        'reserved',
        'available',
        'available',
        'available',
        'available',
        'reserved',
        'reserved',
        'available',
        'reserved',
        'available',
        'reserved',
        'available',
        'available',
        'available',
        'reserved',
        'available',
        'available',
        'available',
        'available',
        'reserved',
        'available',
        'available',
        'available',
        'reserved',
        'available',
        'available',
        'available',
        'reserved',
        'available',
        'available',
        'available',
        'reserved',
        'available',
        'reserved',
        'available',
        'available',
        'reserved',
        'available',
        'available',
        'reserved',
      ]
    },
    {
      title: 'Top Gun: Maverick',
      slug: 'top-gun-maverick',
      // tslint:disable-next-line: max-line-length
      cover: 'https://m.media-amazon.com/images/M/MV5BOTdiNjNjYTUtYzUxZC00NTljLWExYjktZmI0ODQ3ODg5N2U3XkEyXkFqcGdeQXVyNjg3MDMxNzU@._V1_SY1000_CR0,0,679,1000_AL_.jpg',
      trailer: 'https://www.youtube.com/watch?v=qSqVVswa420',
      releaseDate: '23 December 2020',
      duration: '115 minutes',
      // tslint:disable-next-line: max-line-length
      synopsis: `After more than thirty years of service as one of the Navy's top aviators, Pete "Maverick" Mitchell (Tom Cruise) is where he belongs, pushing the envelope as a courageous test pilot and dodging the advancement in rank that would ground him. When he finds himself training a detachment of Top Gun graduates for a specialized mission the likes of which no living pilot has ever seen, Maverick encounters Lt. Bradley Bradshaw (Miles Teller), call sign: "Rooster," the son of Maverick's late friend and Radar Intercept Officer Lt. Nick Bradshaw, aka "Goose". Buy Top Gun: Maverick movie tickets and get showtimes at Regal theatres, on the Regal mobile app or online. Discover movie trailers and view upcoming movies at www.regmovies.com. Stop by a Moviak theater near you today.`,
      genre: 'Action, Drama',
      // tslint:disable-next-line: max-line-length
      cast: `Tom Cruise, Miles Teller, Jennifer Connelly, Jon Hamm, Val Kilmer`,
      Director: 'Joseph Kosinski',
      production: '2020',
      restrictions: 'NR',
      seats: [
        'available',
        'available',
        'reserved',
        'available',
        'available',
        'reserved',
        'available',
        'available',
        'available',
        'available',
        'reserved',
        'available',
        'available',
        'available',
        'available',
        'reserved',
        'reserved',
        'available',
        'available',
        'reserved',
        'available',
        'available',
        'available',
        'available',
        'reserved',
        'reserved',
        'available',
        'available',
        'available',
        'available',
        'available',
        'available',
        'reserved',
        'available',
        'available',
        'available',
        'reserved',
        'available',
        'reserved',
        'available',
        'available',
        'reserved',
        'available',
        'available',
        'reserved',
      ]
    },
    {
      title: 'Wonder Woman 1984',
      slug: 'wonder-woman-1984',
      // tslint:disable-next-line: max-line-length
      cover: 'https://m.media-amazon.com/images/M/MV5BYzAyOGJkMzUtMmRjYS00NGJmLWExNGEtYzI2YjVmMmQzMzFiXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_SY1000_SX675_AL_.jpg',
      trailer: 'https://www.youtube.com/watch?v=sfM7_JLk-84',
      releaseDate: '02 October 2020',
      duration: '115 minutes',
      // tslint:disable-next-line: max-line-length
      synopsis: `Wonder Woman 1984 - Fast forward to the 1980s as Wonder Woman's next big screen adventure finds her facing an all-new foe: The Cheetah. Buy Wonder Woman 1984 movie tickets and get showtimes at Regal theatres, on the Regal mobile app or online. Discover movie trailers and view upcoming movies at www.regmovies.com. Stop by a Moviak theater near you today.`,
      genre: 'Action, Drama',
      // tslint:disable-next-line: max-line-length
      cast: `Chris Pine, Kristen Wiig, Robin Wright, Pedro Pascal, Gal Gadot, Connie Nielsen`,
      Director: 'Patty Jenkins',
      production: '2020',
      restrictions: 'NR',
      seats: [
        'available',
        'available',
        'reserved',
        'available',
        'available',
        'reserved',
        'available',
        'available',
        'available',
        'available',
        'reserved',
        'available',
        'reserved',
        'available',
        'available',
        'reserved',
        'available',
        'available',
        'available',
        'reserved',
        'available',
        'available',
        'available',
        'available',
        'reserved',
        'available',
        'available',
        'reserved',
        'available',
        'available',
        'available',
        'available',
        'reserved',
        'available',
        'available',
        'available',
        'reserved',
        'available',
        'reserved',
        'available',
        'available',
        'reserved',
        'available',
        'available',
        'reserved',
      ]
    },
    {
      title: 'Antebellum',
      slug: 'antebellum',
      // tslint:disable-next-line: max-line-length
      cover: 'https://m.media-amazon.com/images/M/MV5BZmNlOTczOTktMzk3OC00N2RlLTg5NmEtYzNjODBiNzU1NDQxXkEyXkFqcGdeQXVyMjMxOTE0ODA@._V1_SY1000_SX675_AL_.jpg',
      trailer: 'https://www.youtube.com/watch?v=AIrzZ18K_3k',
      releaseDate: '21 August 2020',
      duration: '115 minutes',
      // tslint:disable-next-line: max-line-length
      synopsis: `Antebellum - Successful author Veronica finds herself trapped in a horrifying reality and must uncover the mind-bending mystery before it's too late. Buy Antebellum movie tickets and get showtimes at Regal theatres, on the Regal mobile app or online. Discover movie trailers and view upcoming movies at www.regmovies.com. Stop by a Moviak theater near you today.`,
      genre: 'Action, Drama',
      // tslint:disable-next-line: max-line-length
      cast: `Jack Huston, Kiersey Clemons, Gabourey Sidibe, Jena Malone, Janelle Monáe, Tongayi Chirisa, Marque Richardson II, Eric Lange, Rob Aramayo, Lily Cowles`,
      Director: 'Gerard Bush, Christopher Renz',
      production: '2020',
      restrictions: 'NR',
      seats: [
        'available',
        'available',
        'reserved',
        'available',
        'available',
        'reserved',
        'available',
        'available',
        'available',
        'available',
        'reserved',
        'available',
        'available',
        'available',
        'available',
        'reserved',
        'available',
        'available',
        'available',
        'reserved',
        'available',
        'available',
        'available',
        'available',
        'reserved',
        'available',
        'available',
        'available',
        'available',
        'available',
        'available',
        'available',
        'reserved',
        'available',
        'available',
        'available',
        'reserved',
        'available',
        'reserved',
        'available',
        'available',
        'reserved',
        'available',
        'available',
        'reserved',
      ]
    },
    {
      title: 'A Quiet Place Part II',
      slug: 'a-quiet-place-part-ii',
      // tslint:disable-next-line: max-line-length
      cover: 'https://m.media-amazon.com/images/M/MV5BMmE3OGY2NzMtMGJmOS00NGViLWI4NjYtMjhlNTMxZjA5MDExXkEyXkFqcGdeQXVyMDM2NDM2MQ@@._V1_SY1000_CR0,0,674,1000_AL_.jpg',
      trailer: 'https://www.youtube.com/watch?v=XEMwSdne6UE',
      releaseDate: '04 September 2020',
      duration: '96 minutes',
      // tslint:disable-next-line: max-line-length
      synopsis: `A Quiet Place 2 - Following the deadly events at home, the Abbott family (Emily Blunt, Millicent Simmonds, Noah Jupe) must now face the terrors of the outside world as they continue their fight for survival in silence. Forced to venture into the unknown, they quickly realize that the creatures that hunt by sound are not the only threats that lurk beyond the sand path. Buy A Quiet Place Part II movie tickets and get showtimes at Regal theatres, on the Regal mobile app or online. Discover movie trailers and view upcoming movies at www.regmovies.com. Stop by a Moviak theater near you today.`,
      genre: 'Horror',
      // tslint:disable-next-line: max-line-length
      cast: `Emily Blunt, Cillian Murphy, Djimon Hounsou, Noah Jupe, Millicent Simmonds`,
      Director: 'John Krasinski',
      production: '2020',
      restrictions: 'PG13',
      seats: [
        'available',
        'available',
        'reserved',
        'available',
        'available',
        'reserved',
        'available',
        'available',
        'available',
        'available',
        'reserved',
        'reserved',
        'available',
        'reserved',
        'available',
        'reserved',
        'available',
        'available',
        'available',
        'reserved',
        'available',
        'available',
        'available',
        'available',
        'reserved',
        'available',
        'available',
        'available',
        'reserved',
        'available',
        'available',
        'available',
        'reserved',
        'available',
        'available',
        'available',
        'reserved',
        'available',
        'reserved',
        'available',
        'available',
        'reserved',
        'available',
        'available',
        'reserved',
      ]
    },
    {
      title: 'No Time to Die',
      slug: 'no-time-to-die',
      // tslint:disable-next-line: max-line-length
      cover: 'https://m.media-amazon.com/images/M/MV5BNGEwMDU2ZDQtZmE5Zi00YjFiLWIwYWItOGMyMzY5MzljOWU3XkEyXkFqcGdeQXVyODk2NDQ3MTA@._V1_SY1000_CR0,0,685,1000_AL_.jpg',
      trailer: 'https://www.youtube.com/watch?v=BIhNsAtPbPI',
      releaseDate: '20 November 2020',
      duration: '163 minutes',
      // tslint:disable-next-line: max-line-length
      synopsis: `In No Time To Die, James Bond has left active service and is enjoying a tranquil life in Jamaica. His peace is short-lived when his old friend Felix Leiter from the CIA turns up asking for help. The mission to rescue a kidnapped scientist turns out to be far more treacherous than expected, leading Bond onto the trail of a mysterious villain armed with dangerous new technology. Buy No Time To Die movie tickets and get showtimes at Regal theatres, on the Regal mobile app or online. Discover movie trailers and view upcoming movies at www.regmovies.com. Stop by a Moviak theater near you today.`,
      genre: 'Action',
      // tslint:disable-next-line: max-line-length
      cast: `Ben Whishaw, Daniel Craig, Ralph Fiennes, Jeffrey Wright, Naomie Harris, Rami Malek, Rory Kinnear, Ana de Armas, Lashana Lynch, Billy Magnussen, Léa Seydoux, David Dencik, Dali Benssalah`,
      Director: 'Cary Joji Fukunaga',
      production: '2020',
      restrictions: 'PG13',
      seats: [
        'available',
        'available',
        'reserved',
        'available',
        'available',
        'reserved',
        'available',
        'available',
        'available',
        'available',
        'reserved',
        'available',
        'available',
        'available',
        'available',
        'reserved',
        'reserved',
        'available',
        'available',
        'reserved',
        'available',
        'available',
        'available',
        'available',
        'reserved',
        'reserved',
        'available',
        'available',
        'available',
        'available',
        'available',
        'available',
        'reserved',
        'available',
        'available',
        'available',
        'reserved',
        'available',
        'reserved',
        'available',
        'available',
        'reserved',
        'available',
        'available',
        'reserved',
      ]
    },
    {
      title: 'Croods 2',
      slug: 'croods-2',
      // tslint:disable-next-line: max-line-length
      cover: 'https://regalcdn.azureedge.net/Croods2/HO00010244/TV_SmallPosterImage/20200403-101131371.jpg',
      trailer: 'https://www.youtube.com/watch?v=vh6xso8QAys',
      releaseDate: '23 December 2020',
      duration: '163 minutes',
      // tslint:disable-next-line: max-line-length
      synopsis: `The Croods 2 - The prehistoric family the Croods are challenged by a rival family the Bettermans, who claim to be better and more evolved. Buy The Croods 2 movie tickets and get showtimes at Regal theatres, on the Regal mobile app or online. Discover movie trailers and view upcoming movies at www.regmovies.com. Stop by a Regal theater near you today.`,
      genre: 'Action',
      // tslint:disable-next-line: max-line-length
      cast: `Ryan Reynolds, Emma Stone, Leslie Mann, Nicolas Cage, Cloris Leachman, Kat Dennings, Catherine Keener, Clark Duke`,
      Director: 'Joel Crawford',
      production: '2020',
      restrictions: 'NR',
      seats: [
        'available',
        'available',
        'reserved',
        'available',
        'available',
        'reserved',
        'available',
        'available',
        'available',
        'available',
        'reserved',
        'available',
        'reserved',
        'available',
        'available',
        'reserved',
        'available',
        'available',
        'available',
        'reserved',
        'available',
        'available',
        'available',
        'available',
        'reserved',
        'available',
        'available',
        'reserved',
        'available',
        'available',
        'available',
        'available',
        'reserved',
        'available',
        'available',
        'available',
        'reserved',
        'available',
        'reserved',
        'available',
        'available',
        'reserved',
        'available',
        'available',
        'reserved',
      ]
    },
  ];

  constructor() { }


  allMovies(): {}[] {
    return this.movies;
  }

  getMovie(slug: string): any {
    return this.movies.filter((movie: any) => {
      return movie.slug === slug;
    });
  }

}
